spring:
  application:
    name: hodolog
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hodolog
    username: sa

jwt:
  expiration_time: 86400000 #1일
  secret: aEc1ZG2S9p4CXsEqOkG6t7ibufjy8x+cvhprMlFC2Ag=

hodolman:
  jwt-key: aEc1ZG2S9p4CXsEqOkG6t7ibufjy8x+cvhprMlFC2Ag=